/**
 * Canonical Constants for Privacy-Preserving Browser Agent
 */

export const SENSITIVITY_LEVELS = {
  SAFE: "SAFE",
  SENSITIVE: "SENSITIVE",
  HIGHLY_SENSITIVE: "HIGHLY_SENSITIVE",
} as const;

export const PROTECTION_ACTIONS = {
  KEEP: "KEEP",
  MASK: "MASK",
  REPLACE: "REPLACE",
  BLOCK: "BLOCK",
} as const;

export const ELEMENT_SOURCES = {
  DOM: "DOM",
  OCR: "OCR",
  VISION: "VISION",
} as const;

export const VISION_ELEMENT_TYPES = {
  // UI Interactive Elements
  BUTTON: "BUTTON",
  INPUT: "INPUT",
  SELECT: "SELECT",
  CHECKBOX: "CHECKBOX",
  MODAL: "MODAL",
  ICON: "ICON",
  IMAGE: "IMAGE",
  AVATAR: "AVATAR",
  
  // Sensitive Visual Entities
  FACE: "FACE",
  SIGNATURE: "SIGNATURE",
  DOCUMENT: "DOCUMENT",
  ID_CARD: "ID_CARD",
  QR_CODE: "QR_CODE",
  BARCODE: "BARCODE",
  OTHER: "OTHER",
} as const;

export const AGENT_ACTION_TYPES = {
  CLICK: "CLICK",
  SCROLL: "SCROLL",
  SELECT: "SELECT",
  TYPE_REFERENCE: "TYPE_REFERENCE",
  NAVIGATE: "NAVIGATE",
  WAIT: "WAIT",
  TYPE: "TYPE",
} as const;

export const SECRET_CATEGORIES = {
  EMAIL: "EMAIL",
  PHONE: "PHONE",
  NAME: "NAME",
  CARD: "CARD",
  POLICY: "POLICY",
  ADDRESS: "ADDRESS",
  CUSTOM: "CUSTOM",
} as const;

export const RISK_LEVELS = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  BLOCKED: "BLOCKED",
} as const;

export const SECURITY_POLICY_ERRORS = {
  PASSWORD_STORAGE_FORBIDDEN: "PASSWORDS_EXCLUDED_FROM_SECRET_STORE",
  PASSWORD_AUTOTYPE_FORBIDDEN: "PASSWORD_TARGET_AUTOMATION_FORBIDDEN",
  UNKNOWN_ACTION_VOCABULARY: "UNKNOWN_ACTION_VOCABULARY",
  TARGET_NOT_FOUND: "TARGET_ELEMENT_NOT_FOUND_IN_PAGE",
  TARGET_NOT_INTERACTABLE: "TARGET_ELEMENT_NOT_INTERACTABLE",
  PROMPT_INJECTION_DETECTED: "PROMPT_INJECTION_OR_DANGEROUS_SCRIPT_DETECTED",
  UNAUTHORIZED_NAVIGATION: "UNAUTHORIZED_NAVIGATION_PROTOCOL_OR_DOMAIN",
  INVALID_REFERENCE_TOKEN: "INVALID_OR_EXPIRED_REFERENCE_TOKEN",
  DOMAIN_MISMATCH: "DOMAIN_SCOPE_MISMATCH",
  PAGE_MUTATION_DETECTED: "PAGE_STATE_MUTATED_SINCE_REASONING",
} as const;

export const DEFAULT_SECURITY_THRESHOLDS = {
  PBKDF2_ITERATIONS: 100000,
  AES_KEY_LENGTH: 256,
  IV_LENGTH_BYTES: 12,
  SALT_LENGTH_BYTES: 16,
  MAX_LABEL_LENGTH: 100,
  MAX_VALUE_LENGTH: 4096,
  ACTION_TIMEOUT_MS: 30000,
} as const;

export const DEFAULT_THRESHOLDS = {
  VISION_CONFIDENCE: 0.5,
  OCR_CONFIDENCE: 0.6,
  IOU_NMS_THRESHOLD: 0.45,
  VISUAL_DIFF_SIMILARITY_THRESHOLD: 0.98,
  DEBOUNCE_INFERENCE_MS: 500,
} as const;
